//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcVeteriner_temiz.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GunesliVeterinerEntities : DbContext
    {
        public GunesliVeterinerEntities()
            : base("name=GunesliVeterinerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Crew> Crew { get; set; }
        public virtual DbSet<Gallery> Gallery { get; set; }
        public virtual DbSet<Index3img> Index3img { get; set; }
        public virtual DbSet<IndexSlider> IndexSlider { get; set; }
        public virtual DbSet<LatestWorks> LatestWorks { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
